### PR TITLE
Conversion to glog

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Signed-off-by: ravisantoshgudimetla <ravisantoshgudimetla@gmail.com>

Conversion to glog.

cc @aveshagarwal.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla can you resolve conflicts and resubmit?

**Comment by ravisantoshgudimetla** [comment]
Done. PTAL.

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla thanks. why are all Infof in this PR? Can your further categorize them between errorf, warn, info (and these info as 0,1, 2 levels) as discussed before?

**Comment by ravisantoshgudimetla** [comment]
So, most of the information we are having in fmt.Print seem to be just normal print statements. I thought, we agreed to have level 0 as it is good enough for printing information.

**Comment by ravisantoshgudimetla** [comment]
Also, we need to pass --logtostderr=false when running descheduler or else logging would be redirected to stdout. Should I make this default?

**Pull request merged**
