### PR TITLE
Add preferredDuringSchedulingIgnoredDuringExecution for RemovePodsViolatingNodeAffinity strategy

### PR DESCRIPTION
**Pull request by tsu1980**
I know it's a bit late but I'll leave it here for a record.

Please close if you do not need it.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
Can one of the admins verify this patch?

**Comment by aveshagarwal** [comment]
@tsu1980 thanks for this PR. I will review it soon.

**Comment by J-Swift** [comment]
Hi @aveshagarwal! Any reason this was never merged in? I'm looking to add `PreferredDuringSchedulingIgnoredDuringExecution` support for `pod_antiaffinity` and it would be nice to leverage some of this for the effort.

**Pull request closed without merging**
