### PR TITLE
Yaml files for kubernetes

### PR DESCRIPTION
**Pull request by nicholasklem**
Here is a working setup with yaml files ready to be applied with

`kubectl apply -f .`

Version#2, out of v1beta1 and in v1.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@nicholasklem could you look into "nicholasklem needs CLA"? Sounds like you have not signed CLA?

**Comment by aveshagarwal** [comment]
@nicholasklem nevermind, now its fine.

**Comment by aveshagarwal** [comment]
@nicholasklem lgtm, I am going to merge this, thanks for this PR.

**Comment by nicholasklem** [comment]
Nice!

**Pull request merged**
