### PR TITLE
Added support to evict pods that use local storage.

### PR DESCRIPTION
**Pull request by adyada**
An earlier PR before squashing https://github.com/kubernetes-incubator/descheduler/pull/120

### CODE REVIEW

**Comment by aveshagarwal** [comment]
Can one of the admins verify this patch?

**Comment by aveshagarwal** [comment]
@adyada  Thanks lgtm. I wonder if you could add some unit tests in a follow up PR?

/lgtm

**Comment by rhockenbury** [comment]
@aveshagarwal Are there plans to cut a new release with this change included?

**Comment by aveshagarwal** [comment]
> @aveshagarwal Are there plans to cut a new release with this change included?

@rhockenbury can you give it a test and let me know if it looks good? Then i will cut a new release over the weekend.

**Comment by adyada** [comment]
> @adyada Thanks lgtm. I wonder if you could add some unit tests in a follow up PR?
> 
> /lgtm

Sure, will create a PR for unittest.

**Comment by rhockenbury** [comment]
@aveshagarwal  I've had this running on my clusters for the past month or so and can verify that the `--evict-local-storage-pods` flag is working as expected.

Would you be able to make a new release?  Could you also push an updated image to dockerhub?

**Comment by aveshagarwal** [comment]
@rhockenbury  thanks for your testing, i just cut a new release here: https://github.com/kubernetes-incubator/descheduler/releases/tag/0.9.0

Wonder if you would want to help with official images, see my comment here: https://github.com/kubernetes-incubator/descheduler/issues/144#issuecomment-493033873

**Comment by aveshagarwal** [comment]
@rhockenbury also please lets not use this PR as this is already merged for further comments, lets discuss here for official images: https://github.com/kubernetes-incubator/descheduler/issues/144

**Pull request merged**
