### PR TITLE
Fix deprecated warning in CI

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
I am seeing the following errors in CI continuously.

Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-preflight-errors=all

This should fix the behaviour.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
I am fine as far as you think its ok.

**Comment by ravisantoshgudimetla** [comment]
Alright. Thanks @aveshagarwal . e2es passing and now we are not seeing this error. So, merging it.

**Pull request merged**
