### PR TITLE
Adding golang ci lint support and Refactoring test by make it table driven

### PR DESCRIPTION
**Pull request by reetasingh**
This PR is doing 2 things
1. Add golang-cli lint support
   Also correcting the formatting of some files which are failing the lint checks
2. Refactor some tests to make them table driven (also increases the test coverage)

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@reetasingh thanks for this PR. I will review it soon.

**Comment by reetasingh** [comment]
> @reetasingh thanks for this PR. I will review it soon.

@aveshagarwal Thank you. I want to contribute further and more test cases in this repo once this PR is merged.

**Comment by aveshagarwal** [comment]
@reetasingh could you resolve conflicts in this PR? once you fix it, we can go ahead with merging this PR.

**Comment by reetasingh** [comment]
@aveshagarwal  Sure, I will do that today. Thanks for reviewing the PR.

**Comment by reetasingh** [comment]
@aveshagarwal  I have resolved the merge conflict and rebased my PR. We can go ahead and merge this

**Comment by aveshagarwal** [comment]
/lgtm
/approve

thanks @reetasingh

**Pull request merged**
