### PR TITLE
Modified permissions for gofmt

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
@aveshagarwal Forgot to change permissions. Just checked it and changing it to 644.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
why? 644 is incorrect. I dont see any issue with the current 755.

**Comment by ravisantoshgudimetla** [comment]
I believe we need to have 744(since we are going to execute, apologies), should we allow others to read + execute? I believe its not needed.

**Comment by ravisantoshgudimetla** [comment]
I have accidentally close the PR. I will create one more branch and raise a PR, in case you are fine with @aveshagarwal

**Comment by aveshagarwal** [comment]
giving execute to others for this script is not an issue as it just verifies but does not change anything.

**Comment by ravisantoshgudimetla** [comment]
Ok, I am fine too then.

**Pull request closed without merging**
