### PR TITLE
Changes and file reorganization

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
/cc @aveshagarwal. I wasn't sure about the node ready condition(https://github.com/aveshagarwal/rescheduler/blob/master/pkg/rescheduler/node/node.go#L80). For the rest, I refactored and reorganized functions. Please let me know your feedback.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla the reason I had selected nodes with disk or memory pressure for consideration 
 because it is good to evict pods from them to alleviate their problems.

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla could you discard changes in pkg/rescheduler/node/node.go in these commits?

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla could you fix it soon? I did not realize that your previous PR was dependent upon this PR, and now its breaking unit tests.

**Comment by ravisantoshgudimetla** [comment]
@aveshagarwal Done. PTAL.

**Pull request merged**
