### PR TITLE
[WIP] End to testing PR

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
@aveshagarwal Please check vendor updates at f8a9031 and code changes in 3a02e16

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla where is ./test-e2e.sh as per your README? I dont see that file in this PR.

**Comment by ravisantoshgudimetla** [comment]
Done @aveshagarwal. PTAL.

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla I am a bit confused. How is the test script `test/e2e/test-e2e.sh` running `test/e2e/e2e_test.go`?

**Comment by ravisantoshgudimetla** [comment]
Closing this in favor of #31

**Pull request closed without merging**
